let a = 'hello';
let b = 'owu';
let c = 'com';
let d = 'ua';
let e = 1;
let f = 10;
let g = -999;
let h = 123;
let i = 3.14;
let j = 2.7;
let k = 16;
let l = true;
let m = false;
console.log(a, b, c, d, e, f, g, h, i, j, k, l, m);
document.write(a, b, c, d, e, f, g, h, i, j, k, l, m);
alert(a);
alert(b);
alert(c);
alert(d);
alert(e);
alert(f);
alert(g);
alert(h);
alert(i);
alert(j);
alert(k);
alert(l);
alert(m);
let firstName = 'Valentyna';
let middleName = 'Pavlivna';
let lastName = 'Plakhtii';
let person = firstName +' '+ middleName +' '+ lastName;
console.log (person)
let ab = 100;
let bc = '100';
let cd = true;
console.log(typeof ab, typeof bc, typeof cd);
let result = prompt('first name', 'Valentyna');
let result2 = prompt('middle name', 'Pavlivna');
let result3 = prompt('date of birth', '26.12.1996');
console.log(result, result2, result3);